name: flutter_platform_alert
description: A plugin helps to call native API to play alert sound and show alert dialogs. For example, it bridges MessageBox and TaskDialogIndirect on Windows.
version: 0.2.7
homepage: https://github.com/zonble/flutter_platform_alert

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: net.zonble.flutter_platform_alert
        pluginClass: FlutterPlatformAlertPlugin
      ios:
        pluginClass: FlutterPlatformAlertPlugin
      macos:
        pluginClass: FlutterPlatformAlertPlugin
      windows:
        pluginClass: FlutterPlatformAlertPlugin
      linux:
        pluginClass: FlutterPlatformAlertPlugin

  