
name: Linux

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.x' # you can use 1.12
        channel: 'stable' 
    - name: Upgrades Flutter
      run: flutter upgrade
      working-directory: ./example
    - name: Enables Linux desktop
      run: flutter config --enable-linux-desktop
      working-directory: ./example
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./example
    - name: Build Linux
      run: flutter build linux
      working-directory: ./example
